import java.awt.*;
import javax.swing.*;

import modfiles.RoundedBorder;

public class BaseScreenStructure extends JFrame {
    
    int frameheight = 620;          
    int framewidth = 960;
    int panelheight = 400;
    int panelwidth = 650;

    protected JPanel centerpanel;

    public BaseScreenStructure(){
        
        //Main Frame details
        setSize(framewidth,frameheight);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.BLACK);
        setResizable(false);
        setLayout(null);    
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        //Top right details
        JLabel toprightlabel = new JLabel("AeroX");
        toprightlabel.setFont(new Font("Calibri",Font.BOLD,24));
        toprightlabel.setForeground(Color.WHITE);
        toprightlabel.setBackground(Color.BLACK);
        toprightlabel.setBounds(868,10,80,30);
        add(toprightlabel);

        //Footer details
        JLabel footer = new JLabel("AeroX © 2025");
        footer.setFont(new Font("Calibri",Font.PLAIN,18));
        footer.setForeground(Color.WHITE);
        footer.setBackground(Color.BLACK);
        footer.setBounds(420,550,200,30);
        add(footer);

        //Center Panel details
        centerpanel = new JPanel();
        centerpanel.setBackground(Color.BLACK);
        centerpanel.setBounds(155,95,panelwidth,panelheight);
        //centerpanel.setBorder(new LineBorder(Color.WHITE,2, true));            ->  not enough round edges
        centerpanel.setBorder(new RoundedBorder(Color.WHITE, 2, 80)); //custom rounded Border generated by chatgpt
        centerpanel.setLayout(null);
        add(centerpanel);


        // setVisible(true);
    }

    // public static void main(String[] args) {
    //     new BaseScreenStructure();
    // }


}
